name: Run Docker Container

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull amaan1609/dappier-job-app-api:latest
    - name: Delete Old docker container
      run: sudo docker rm -f dappier-job-app-api-container || true
    - name: Run Docker Container
      run: sudo docker run -d -e MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING -p 8080:8080 --name dappier-job-app-api-container amaan1609/dappier-job-app-api
