name: Run Docker Container

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull amaan1609/dappier-job-app-api:latest
    - name: Delete Old docker container
      run: sudo docker rm -f dappier-job-app-api-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name dappier-job-app-api-container \-e MONGO_CONNECTION_STRING="mongodb+srv://amaan1609:1234@cluster0.hpo5k.mongodb.net/DappierJobApp?retryWrites=true&w=majority&appName=Cluster0"\ amaan1609/dappier-job-app-api

